// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        string             `json:"id"`
	RoomID    string             `json:"room_id"`
	UserID    string             `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Report struct {
	ID         string             `json:"id"`
	MessageID  string             `json:"message_id"`
	ReporterID string             `json:"reporter_id"`
	Reason     string             `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
	IsActive       pgtype.Bool        `json:"is_active"`
}

type RoomPresence struct {
	RoomID     string             `json:"room_id"`
	UserID     string             `json:"user_id"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

type User struct {
	ID          string             `json:"id"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	Status      pgtype.Text        `json:"status"`
}
