// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRoom(ctx context.Context, id string) (Room, error)
	GetRoomMessages(ctx context.Context, arg GetRoomMessagesParams) ([]Message, error)
	GetUser(ctx context.Context, id string) (User, error)
	ListActiveRooms(ctx context.Context, arg ListActiveRoomsParams) ([]Room, error)
}

var _ Querier = (*Queries)(nil)
