// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRoom(ctx context.Context, id string) (Room, error)
	GetRoomByJoinCode(ctx context.Context, joinCode pgtype.Text) (Room, error)
	GetRoomMessages(ctx context.Context, arg GetRoomMessagesParams) ([]GetRoomMessagesRow, error)
	GetRoomPresenceCount(ctx context.Context, roomID string) (int64, error)
	GetUser(ctx context.Context, id string) (User, error)
	ListActiveRooms(ctx context.Context, arg ListActiveRoomsParams) ([]Room, error)
	ListReports(ctx context.Context, arg ListReportsParams) ([]ListReportsRow, error)
	RemovePresence(ctx context.Context, arg RemovePresenceParams) error
	SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) error
	UpsertPresence(ctx context.Context, arg UpsertPresenceParams) error
}

var _ Querier = (*Queries)(nil)
