// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, room_id, user_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, room_id, user_id, content, created_at, deleted_at
`

type CreateMessageParams struct {
	ID      string `json:"id"`
	RoomID  string `json:"room_id"`
	UserID  string `json:"user_id"`
	Content string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.RoomID,
		arg.UserID,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (id, message_id, reporter_id, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, message_id, reporter_id, reason, created_at
`

type CreateReportParams struct {
	ID         string `json:"id"`
	MessageID  string `json:"message_id"`
	ReporterID string `json:"reporter_id"`
	Reason     string `json:"reason"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ID,
		arg.MessageID,
		arg.ReporterID,
		arg.Reason,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ReporterID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (id, name, description, is_private, join_code)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, created_at, last_activity_at, is_active, is_private, join_code
`

type CreateRoomParams struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsPrivate   pgtype.Bool `json:"is_private"`
	JoinCode    pgtype.Text `json:"join_code"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsPrivate,
		arg.JoinCode,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.IsActive,
		&i.IsPrivate,
		&i.JoinCode,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, display_name)
VALUES ($1, $2)
RETURNING id, display_name, created_at, last_seen_at, status
`

type CreateUserParams struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.Status,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT id, name, description, created_at, last_activity_at, is_active, is_private, join_code FROM rooms
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoom(ctx context.Context, id string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.IsActive,
		&i.IsPrivate,
		&i.JoinCode,
	)
	return i, err
}

const getRoomByJoinCode = `-- name: GetRoomByJoinCode :one
SELECT id, name, description, created_at, last_activity_at, is_active, is_private, join_code FROM rooms
WHERE join_code = $1 AND is_active = true LIMIT 1
`

func (q *Queries) GetRoomByJoinCode(ctx context.Context, joinCode pgtype.Text) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByJoinCode, joinCode)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.IsActive,
		&i.IsPrivate,
		&i.JoinCode,
	)
	return i, err
}

const getRoomMessages = `-- name: GetRoomMessages :many
SELECT id, room_id, user_id, content, created_at, deleted_at FROM messages
WHERE room_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetRoomMessagesParams struct {
	RoomID string `json:"room_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetRoomMessages(ctx context.Context, arg GetRoomMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getRoomMessages, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomPresenceCount = `-- name: GetRoomPresenceCount :one
SELECT COUNT(*) FROM room_presence
WHERE room_id = $1 AND last_seen_at > CURRENT_TIMESTAMP - INTERVAL '5 minutes'
`

func (q *Queries) GetRoomPresenceCount(ctx context.Context, roomID string) (int64, error) {
	row := q.db.QueryRow(ctx, getRoomPresenceCount, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUser = `-- name: GetUser :one
SELECT id, display_name, created_at, last_seen_at, status FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.Status,
	)
	return i, err
}

const listActiveRooms = `-- name: ListActiveRooms :many
SELECT id, name, description, created_at, last_activity_at, is_active, is_private, join_code FROM rooms
WHERE is_active = true AND is_private = false
ORDER BY last_activity_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveRoomsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveRooms(ctx context.Context, arg ListActiveRoomsParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listActiveRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.LastActivityAt,
			&i.IsActive,
			&i.IsPrivate,
			&i.JoinCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReports = `-- name: ListReports :many
SELECT r.id, r.message_id, r.reporter_id, r.reason, r.created_at, 
       m.content as message_content, m.user_id as message_author_id
FROM reports r
JOIN messages m ON r.message_id = m.id
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type ListReportsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListReportsRow struct {
	ID              string             `json:"id"`
	MessageID       string             `json:"message_id"`
	ReporterID      string             `json:"reporter_id"`
	Reason          string             `json:"reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	MessageContent  string             `json:"message_content"`
	MessageAuthorID string             `json:"message_author_id"`
}

func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]ListReportsRow, error) {
	rows, err := q.db.Query(ctx, listReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportsRow
	for rows.Next() {
		var i ListReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ReporterID,
			&i.Reason,
			&i.CreatedAt,
			&i.MessageContent,
			&i.MessageAuthorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePresence = `-- name: RemovePresence :exec
DELETE FROM room_presence
WHERE room_id = $1 AND user_id = $2
`

type RemovePresenceParams struct {
	RoomID string `json:"room_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) RemovePresence(ctx context.Context, arg RemovePresenceParams) error {
	_, err := q.db.Exec(ctx, removePresence, arg.RoomID, arg.UserID)
	return err
}

const softDeleteMessage = `-- name: SoftDeleteMessage :exec
UPDATE messages 
SET deleted_at = CURRENT_TIMESTAMP 
WHERE id = $1 AND user_id = $2
`

type SoftDeleteMessageParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) error {
	_, err := q.db.Exec(ctx, softDeleteMessage, arg.ID, arg.UserID)
	return err
}

const upsertPresence = `-- name: UpsertPresence :exec
INSERT INTO room_presence (room_id, user_id, last_seen_at)
VALUES ($1, $2, CURRENT_TIMESTAMP)
ON CONFLICT (room_id, user_id) 
DO UPDATE SET last_seen_at = CURRENT_TIMESTAMP
`

type UpsertPresenceParams struct {
	RoomID string `json:"room_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpsertPresence(ctx context.Context, arg UpsertPresenceParams) error {
	_, err := q.db.Exec(ctx, upsertPresence, arg.RoomID, arg.UserID)
	return err
}
